name: Harvest OAI data from all OJS instances from the last 30 days
on:
  schedule:
    - cron: '30 19 * * 6'
  workflow_dispatch:
jobs:
  harvest-oai:
    strategy:
      matrix:
        endpoints:
          - { set: "aavpt", url: "https://aavptbiennial-ojs-tamu.tdl.org/aavptbiennial/oai" }
          - { set: "awl", url: "https://awl-ojs-tamu.tdl.org/awl/oai" }
          - { set: "watchbird", url: "https://watchbird-ojs-tamu.tdl.org/watchbird/oai" }
          - { set: "bovine", url: "https://bovine-ojs-tamu.tdl.org/AABP/oai" }
          - { set: "ciney", url: "https://ciney-ojs-tamu.tdl.org/ciney/oai" }
          - { set: "icce", url: "https://icce-ojs-tamu.tdl.org/icce/oai" }
          - { set: "dlrpj", url: "https://dlrpj-ojs-tamu.tdl.org/dlrpj/oai" }
          - { set: "ertr", url: "https://ertr-ojs-tamu.tdl.org/ertr/oai" }
          - { set: "epbj", url: "https://epbj-ojs-tamu.tdl.org/epbj/oai" }
          - { set: "hpr", url: "https://hpr-ojs-tamu.tdl.org/hpr/oai" }
          - { set: "instars", url: "https://instars-ojs-tamu.tdl.org/instars/oai" }
          - { set: "jaawge", url: "https://jaawge-ojs-tamu.tdl.org/jaawge/oai" }
          - { set: "jfe", url: "https://jfe-ojs-tamu.tdl.org/jfe/oai" }
          - { set: "regsci", url: "https://regsci-ojs-tamu.tdl.org/regsci/oai" }
          - { set: "jume", url: "https://jume-ojs-tamu.tdl.org/jume/oai" }
          - { set: "paj", url: "https://paj-ojs-tamu.tdl.org/paj/oai" }
          - { set: "pal", url: "https://pal-ojs-tamu.tdl.org/pal/oai" }
          - { set: "bovine2", url: "https://bovine-ojs-tamu.tdl.org/bovine/oai" }
          - { set: "ijcs", url: "https://ijscs-ojs-tamu.tdl.org/ijscs/oai" }
          - { set: "jfse", url: "https://jfse-ojs-tamu.tdl.org/jfse/oai" }
          - { set: "tndr", url: "https://tndr-ojs-tamu.tdl.org/tndr/oai"}
    name: Harvest OAI
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.2"
      - name: Install application
        run: poetry install
      - name: Harvest
        run: poetry run ojs-harvester harvest -e "${{ matrix.endpoints.url }}" -o ${{ matrix.endpoints.set }}
      - name: Commit and push if it changed
        run: |-
          git config user.name "markpbaggett"
          git config user.email "markpbaggett@gmail.com"
          git add -A
          timestamp=$(date -u)
          git pull origin main
          git commit -m "Harvest metadata for ${{ matrix.endpoints.set }} at ${timestamp}" || exit 0
          git push
